source:      .
destination: ./_site
includes:    ./_includes
# baseurl: /xiaohe

collections:
  projects:
    output: true

defaults:
  - scope:
      path: "assets/blog"
    values:
      layout: "blog"
